bot_site/bot/urls.py
from django.urls import path
from . import views
 
app_name = "bot"
urlpatterns = [
    path('', views.index, name='index'),

    path('houses/', views.HouseListView.as_view(), name='houses'),
    path('house/<int:pk>/', views.HouseDetailView.as_view(), name='house-detail'),
    path('questions/', views.QuestionListView.as_view(), name='questions'),
    path('question/<int:pk>/', views.QuestionDetailView.as_view(), name='question-detail'),

    path('house/create/', views.HouseCreate.as_view(), name='house-create'),
    path('house/<int:pk>/update/', views.HouseUpdate.as_view(), name='house-update'),
    path('house/<int:pk>/delete/', views.HouseDelete.as_view(), name='house-delete'),

    path('question/create/', views.QuestionCreate.as_view(), name='question-create'),
    path('question/<int:pk>/update/', views.QuestionUpdate.as_view(), name='question-update'),
    path('question/<int:pk>/delete/', views.QuestionDelete.as_view(), name='question-delete'),

    path('photos/', views.PhotosListView.as_view(), name='photos'),
    path('videos/', views.VideosListView.as_view(), name='videos'),

    path('prompts/', views.update_prompts, name='prompts-update'),
    path('newsletter/', views.send_newsletter, name='newsletter'),

    #DEBUG, SHOULD REMOVE!!!
    path('create_queue', views.create_queue),
]

bot_site/bot_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bot.urls'), name='home'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.custom_logout, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bot_site/bot/models.py
import os
from time import sleep

from django.db import models
from django.db.models.signals import pre_delete, post_save
from django.dispatch import receiver
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from pika import BlockingConnection, ConnectionParameters, URLParameters
from bot_management.conf import (RABBITMQ_LOGIN, RABBITMQ_PASSWORD,
                                 RABBITMQ_QUEUE_NAME, RABBITMQ_HOST_NAME,
                                 RABBITMQ_CONNECT_RETRIES, DELAY_BETWEEN_RETRIES)

class Photo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text=_("photo owner"))
    photo = models.ImageField()
    house = models.ForeignKey('House', verbose_name=_('house'), on_delete=models.CASCADE, blank=True, null=True)
    question = models.ForeignKey('Question', verbose_name=_('question'), on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{str(self.photo)}"

    class Meta:
        verbose_name = _("photo")
        verbose_name_plural = _("photos")

@receiver(post_save, sender=User)
def create_rabbitmq_queue(sender, instance, created, **kwargs):
    if created:
        for attempt_number in range(1, RABBITMQ_CONNECT_RETRIES + 1):
            try:
                connection = BlockingConnection(URLParameters(f"amqp://{RABBITMQ_LOGIN}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST_NAME}/"))
                if connection:
                    print("Successfully connected to RabbitMQ")
                    break
            except Exception as ex:
                sleep(DELAY_BETWEEN_RETRIES)
                print(ex)
                print(f"Failed to connect to RabbitMQ. Retrying...(attempt number {attempt_number})")
        else:
            print("Failed to connect... Exiting")
            return
        channel = connection.channel()
        queue_name = RABBITMQ_QUEUE_NAME + str(instance.id)
        queue = channel.queue_declare(queue_name, durable=True)
        channel.queue_bind(exchange="amq.direct", queue=queue_name, routing_key=queue_name)
        connection.close()


@receiver(pre_delete, sender=Photo)
def photo_pre_delete(sender, instance, **kwargs):
    if instance.photo:
        if os.path.isfile(instance.photo.path):
            os.remove(instance.photo.path)

class Video(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.FileField()
    question = models.ForeignKey('Question', verbose_name=_('question'), on_delete=models.CASCADE, 
        blank=True, null=True, help_text=_("related question"))

    def __str__(self):
        return f"{self.video}"

    class Meta:
        verbose_name = _("video")
        verbose_name_plural = _("videos")
    

@receiver(pre_delete, sender=Video)
def video_pre_delete(sender, instance, **kwargs):
    if instance.video:
        if os.path.isfile(instance.video.path):
            os.remove(instance.video.path)


class House(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    house_number = models.PositiveIntegerField(verbose_name=_('house number'))
    house_name = models.CharField(verbose_name=_('house name'), max_length=100, blank=True, null=True)
    address = models.CharField(verbose_name=_('address'), max_length=100)

    def __str__(self):
        return f"{self.house_number}. {self.house_name} ({self.address})"
    
    def get_absolute_url(self):
        return reverse('bot:house-detail', args=[str(self.id)])

    class Meta:
        verbose_name = _("house")
        verbose_name_plural = _("houses")


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question_number = models.PositiveIntegerField(verbose_name=_('question number'))
    question_text = models.TextField(verbose_name=_('question text'), max_length=200)
    answer_text = models.TextField(verbose_name=_('answer text'), max_length=2000)
    house = models.ForeignKey(House, verbose_name=_('house'), on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.question_text}"
    
    def get_absolute_url(self):
        return reverse('bot:question-detail', args=[str(self.id)])

    class Meta:
        unique_together = ("question_number", "house")
        verbose_name = _("question")
        verbose_name_plural = _("questions")


class Prompt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    prompt_name = models.CharField(verbose_name=_('prompt name'), max_length=100)
    prompt = models.TextField(verbose_name=_('prompt text'), max_length=1000)
    helper_text = models.CharField(verbose_name=_('prompt helper text'), max_length=100)

    def __str__(self):
        return f"(prompt) {self.prompt_name}"

    class Meta:
        verbose_name = _("сообщение")
        verbose_name_plural = _("сообщения")
    

class RegisteredUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tg_user_id = models.PositiveIntegerField()

    class Meta:
        unique_together = ('user', 'tg_user_id')
        verbose_name = _("registered user")
        verbose_name_plural = _("registered users")


bot_site/bot/views.py
import json
from typing import Any
from django.db.models.query import QuerySet
from django.forms import inlineformset_factory, modelformset_factory
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.shortcuts import get_object_or_404
from django.db import connection as db_connection
from django.http import HttpResponseServerError
from time import sleep


from .models import House, Question, Photo, Video, Prompt
from .forms import (PhotoForm, HouseForm, QuestionForm, 
                    VideoForm, create_custom_formset, 
                    PhotoFormSet, VideoFormSet, PromptForm,
                    PromptFormSet, NewsletterForm)

from pika import BlockingConnection, URLParameters
from pika.exceptions import ChannelClosedByBroker
from bot_management.conf import RABBITMQ_LOGIN, RABBITMQ_PASSWORD, RABBITMQ_QUEUE_NAME, RABBITMQ_HOST_NAME

@login_required
def index(request):
    # Home page, should redirect to login if user is not authenticated
    # else show some page like "Hello, very happy to see you"
    return render(request, "bot/index.html")


class HouseAccessMixin(UserPassesTestMixin):
    def test_func(self):
        house = get_object_or_404(House, pk=self.kwargs['pk'])
        return self.request.user == house.user


class HouseDetailView(LoginRequiredMixin, HouseAccessMixin, generic.DetailView):
    model = House
    form_class = HouseForm
    def get_queryset(self):
        return House.objects.filter(user=self.request.user)


class HouseListView(LoginRequiredMixin, generic.ListView):
    model = House

    def get_queryset(self):
        return House.objects.filter(user=self.request.user).order_by('house_number')
    

class QuestionAccessMixin(UserPassesTestMixin):
    def test_func(self):
        question = get_object_or_404(Question, pk=self.kwargs['pk'])
        return self.request.user == question.user
    

class QuestionDetailView(LoginRequiredMixin, QuestionAccessMixin, generic.DetailView):
    model = Question

    def get_queryset(self):
        return Question.objects.filter(user=self.request.user)
    

class QuestionListView(LoginRequiredMixin, generic.ListView):
    model = Question

    def get_queryset(self):
        queryset = Question.objects.filter(user=self.request.user).order_by('question_number')
        house_filter = self.request.GET.get('house_choice')
        if house_filter:
            queryset = queryset.filter(house=house_filter)
        return queryset

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        id_list = list(Question.objects.values_list('house', flat=True).distinct())
        ctx['filter_house_list'] = House.objects.filter(user=self.request.user, pk__in=id_list)
        return ctx


class PhotosListView(LoginRequiredMixin, generic.ListView):
    model = Photo

    def get_queryset(self):
        return Photo.objects.filter(user=self.request.user)
    

class VideosListView(LoginRequiredMixin, generic.ListView):
    model = Video

    def get_queryset(self):
        return Video.objects.filter(user=self.request.user)

class HouseCreate(LoginRequiredMixin, CreateView):
    model = House
    form_class = HouseForm
    
    def get_context_data(self, **kwargs):
        ctx = super(HouseCreate, self).get_context_data(**kwargs)
        ctx['photos'] = create_custom_formset(House, Photo, PhotoForm, fields=['photo'])() if 'photos' not in kwargs else kwargs['photos']
        return ctx
    
    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        photoformset = create_custom_formset(House, Photo, PhotoForm)(self.request.POST, self.request.FILES)
        if form.is_valid() and photoformset.is_valid():
            return self.form_valid(form, photoformset)
        else:
            return self.form_invalid(form, photoformset)
        
    def form_valid(self, form, photoformset):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        form.save()
        photoformset.save(self.request.user, self.object)
        return redirect(reverse('bot:house-detail', args=[self.object.id]))
    
    def form_invalid(self, form, photoformset):
        return self.render_to_response(
            self.get_context_data(form=form, photos=photoformset)
        )
    

class HouseUpdate(LoginRequiredMixin, HouseAccessMixin, UpdateView):
    model = House
    form_class = HouseForm

    def get_context_data(self, **kwargs):
        ctx = super(HouseUpdate, self).get_context_data(**kwargs)
        ctx['photos'] = create_custom_formset(House, Photo, PhotoForm, fields=['photo'])(instance=self.object)
        return ctx
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        photoformset = create_custom_formset(House, Photo, PhotoForm)(
            self.request.POST, 
            self.request.FILES,
            instance=self.object)
        if form.is_valid() and photoformset.is_valid():
            return self.form_valid(form, photoformset)
        else:
            return self.form_invalid(form, photoformset)
        
    def form_valid(self, form, photoformset):
        form.save()
        for deleted_form in photoformset.deleted_forms:
            deleted_form.instance.delete()
        photoformset.save(self.request.user, self.object)
        return redirect(reverse('bot:house-detail', args=[self.object.id]))
    
    def form_invalid(self, form, photoformset):
        return self.render_to_response(
            self.get_context_data(form=form, photos=photoformset)
        )



class HouseDelete(LoginRequiredMixin, HouseAccessMixin, DeleteView):
    model = House
    success_url = reverse_lazy('bot:houses')

    def form_valid(self, form):
        try:
            self.object.delete()
            return redirect(self.success_url)
        except Exception as ex:
            return redirect(reverse("bot:house-delete", kwargs={"pk": self.object.pk}))



class QuestionCreate(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # ctx['photos'] = PhotoFormSet(queryset=Photo.objects.none()) if 'photos' not in kwargs else kwargs['photos']
        # ctx['videos'] = VideoFormSet(queryset=Video.objects.none()) if 'videos' not in kwargs else kwargs['videos']
        ctx['photos'] = inlineformset_factory(Question, Photo, form=PhotoForm, fields=['photo'], can_delete_extra=False, extra=1)()
        ctx['videos'] = inlineformset_factory(Question, Video, form=VideoForm, fields=['video'], can_delete_extra=False, extra=1)()
        return ctx
    
    def post(self, request, *args, **kwargs):
        # photoformset = PhotoFormSet(self.request.POST, self.request.FILES)
        photoformset = inlineformset_factory(Question, Photo, form=PhotoForm, fields=['photo'], can_delete_extra=False, extra=1)(
            self.request.POST, 
            self.request.FILES
            )
        # videoformset = VideoFormSet(self.request.POST, self.request.FILES)
        videoformset = inlineformset_factory(Question, Video, form=VideoForm, fields=['video'], can_delete_extra=False, extra=1)(
            self.request.POST, 
            self.request.FILES
            )
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid() and photoformset.is_valid() and videoformset.is_valid():
            return self.form_valid(form, photoformset, videoformset)
        else:
            return self.form_invalid(form, photoformset, videoformset)
        
    def form_valid(self, form, photoformset, videoformset):
        question = form.save(commit=False)
        question.user = self.request.user
        question.save()
        photos = photoformset.save(commit=False)
        videos = videoformset.save(commit=False)
        for photo in photos:
            photo.user = self.request.user
            photo.question = question
            photo.save()
        for video in videos:
            video.user = self.request.user
            video.question = question
            video.save()
        question.save()
        return redirect(reverse('bot:question-detail', args=[str(question.id)]))
    
    def form_invalid(self, form, photoformset, videoformset):
        return self.render_to_response(
            self.get_context_data(form=form, photos=photoformset, videos=videoformset)
        )


class QuestionUpdate(LoginRequiredMixin, QuestionAccessMixin, UpdateView):
    model = Question
    form_class = QuestionForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # ctx['photos'] = PhotoFormSet(instance=self.object)
        ctx['photos'] = inlineformset_factory(Question, Photo, form=PhotoForm, fields=['photo'], can_delete_extra=False, extra=1)(instance=self.object)

bot_site/bot/templates/bot/base_generic.html
{% load i18n %}

<!DOCTYPE html>
<html>
  <head>
    {% block title %}
      <title>{% translate "Bot management" %}</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'bot/css/style.css' %}">
    {% block head_addition %} {% endblock %}
    <!-- Add additional CSS in static file -->
    <!-- {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}" /> -->
  </head>
  <body>
    <header class="header">
      <a href="#" class="logo">Logo</a>

      <nav class="navbar">
        <ul class="sidebar">
          <li onclick=hideSidebar()><a href="#"><svg xmlns="http://www.w3.org/2000/svg" height="40" viewBox="0 -960 960 960" width="40"><path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"/></svg></a></li>
          <li><a href="{% url 'bot:prompts-update' %}">{% translate "Prompts" %}</a></li>
          <li><a href="{% url 'bot:newsletter' %}">{% translate "Newsletter" %}</a></li>
          <li><a href="{% url 'bot:houses' %}">{% translate "Houses" %}</a></li>
          <li><a href="{% url 'bot:questions' %}">{% translate "Questions" %}</a></li>
          <li><a href="{% url 'logout' %}" class="btn">{% translate "Logout" %}</a></li>
        </ul>
        <ul class="nav-header">
          {% url 'bot:index' as index_path %}
          <li class="hideOnMobile {% if request.path == index_path %}choosen-link{% endif %}" ><a href="{% url 'bot:index' %}">{% translate "Home" context "home page" %}</a></li>
          {% url 'bot:prompts-update' as prompts_path %}
          <li class="hideOnMobile {% if request.path == prompts_path %}choosen-link{% endif %}"><a href="{% url 'bot:prompts-update' %}">{% translate "Prompts" %}</a></li>
          {% url 'bot:newsletter' as newletter_path %}
          <li class="hideOnMobile {% if request.path == newletter_path %}choosen-link{% endif %}"><a href="{% url 'bot:newsletter' %}">{% translate "Newsletter" %}</a></li>
          {% url 'bot:houses' as houses_path %}
          <li class="hideOnMobile {% if request.path == houses_path %}choosen-link{% endif %}"><a href="{% url 'bot:houses' %}">{% translate "Houses" %}</a></li>
          {% url 'bot:questions' as questions_path %}
          <li class="hideOnMobile {% if request.path == questions_path %}choosen-link{% endif %}"><a href="{% url 'bot:questions' %}">{% translate "Questions" %}</a></li>
          <li class="hideOnMobile"><a href="{% url 'logout' %}" class="btn">{% translate "Logout" %}</a></li>
          <li class="menu-button" onclick=showSidebar()><a href="#"><svg xmlns="http://www.w3.org/2000/svg" height="40" viewBox="0 -960 960 960" width="40"><path d="M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z"/></svg></a></li>
        </ul>
      </nav>
    </header>
    <div class="content">
      {% block content %}
      {% endblock %}
    </div>
    {% block scripts %}{% endblock %}
    <script type="text/javascript" src="{% static 'bot/js/main.js' %}"></script>
  </body>
</html>

bot_site/bot/templates/bot/house_list.html
{% extends "bot/base_generic.html" %}

{% load i18n %}

{% block head_addition %}
{% load static %}
<link rel="stylesheet" href="{% static 'bot/css/style.css' %}">
<link rel="stylesheet" href="{% static 'bot/css/prompts.css' %}">
{% endblock %}

{% block content %}
	{% load bot_extras %}
	<h1>{% translate "Your houses" %}</h1>
	<a href="{% url 'bot:house-create' %}" class="btn">{% translate "Add House" %}</a>
	{% if house_list %}
		{% for house in house_list %}
			<div class="house-card">
				<div class="image-buttons">
					<div class="image-buttons-image">
						{% with first_photo=house.photo_set.all|first%}
						<a href="{% url 'bot:house-detail' house.pk %}"><img src="{{first_photo.photo.url}}" alt=""></a>
						{% endwith %}
					</div>
					<div class="image-buttons-buttons">
						<a href="{% url 'bot:house-update' house.pk %}" class="house-btn">{% translate "Edit" %}</a>
						<a href="{% url 'bot:house-delete' house.pk %}" class="house-btn">{% translate "Delete" %}</a>
					</div>
				</div>
				<div class="card-content">
					<div class="card-content-row">
						<label for="">{{house|verbose_name:"house_number"}}:</label>
						{{house.house_number}}
					</div>
					<div class="card-content-row">
						<label for="">{{house|verbose_name:"house_name"}}: </label>
						{{ house.house_name }}
					</div>
					<div class="card-content-row">
						<label for="">{{house|verbose_name:"address"}}:</label>
						{{house.address}}
					</div>
				</div>
			</div>
		{% endfor %}
	{% else %}
		<p>{% translate "There are no added houses." %}</p>
	{% endif %}
{% endblock %}

bot_site/bot/templates/bot/index.html
{% extends "bot/base_generic.html" %}

{% load i18n %}

{% block content %}
<h1>{% translate "Welcome" %}!</h1>
<p>{% translate "Glad to see you there" %}!</p>
{% endblock %}

bot_site/bot/templates/bot/photo_list.html
{% extends "bot/base_generic.html" %}

{% load i18n %}

{% block content %}
<h1>Your Photos</h1>
{% if photo_list %}
<ul>
    {% for photo in photo_list %}
    <li>
        <a href="{{ photo.photo.url }}">{{ photo.photo }}</a>
        <img src="{{ photo.photo.url }}" style="max-height:200px;">
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no added photos.</p>
{% endif %}
{% endblock %}

bot_site/bot/templates/bot/question_detail.html
{% extends "bot/base_generic.html" %}

{% load bot_extras %}
{% load i18n %}

{% block head_addition %}
{% load static %}
	<!-- Подключение стилей Glide.js -->
	<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@glidejs/glide/dist/css/glide.core.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@glidejs/glide/dist/css/glide.theme.min.css"> -->
	<link rel="stylesheet" href="{% static 'bot/css/glide.core.min.css' %}">
	<link rel="stylesheet" href="{% static 'bot/css/glide.theme.min.css' %}">

	<!-- Подключение скриптов Glide.js и его зависимостей (Popper.js и Splide.js) -->
	<!-- <script src="https://cdn.jsdelivr.net/npm/@glidejs/glide"></script>
	<script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
	<script src="https://unpkg.com/splide@2.0.0/dist/js/splide.js"></script> -->
	<script src="{% static 'bot/js/glide.js' %}"></script>
	<script src="{% static 'bot/js/popper.min.js' %}"></script>

	<link rel="stylesheet" href="{% static 'bot/css/question_detail.css' %}">
    <link rel="stylesheet" href="{% static 'bot/css/style.css' %}">
{% endblock %}

{% block content %}

<div class="question-card">
	<h1>{% translate "Question details" %}</h1>
	<div class="media-container">
		{% if question.photo_set.all %}
			<div class="glide-container" id="photo-carousel">
				<div class="glide">
					<div class="glide__track" data-glide-el="track">
						<ul class="glide__slides">
							{% for photo in question.photo_set.all %}
							<li class="glide__slide"><img src="{{photo.photo.url}}" alt="" class="question-detail-image"></li>
							{% endfor %}
						</ul>
					</div>
					<!-- <div class="glide__arrows" data-glide-el="controls">
						<button class="glide__arrow glide__arrow--left" data-glide-dir="<">{% translate "prev" context "carousel button" %}</button>
						<button class="glide__arrow glide__arrow--right" data-glide-dir=">">{% translate "next" context "carousel button" %}</button>
					</div> -->
					<div class="glide__bullets" data-glide-el="controls[nav]">
						{% for photo in question.photo_set.all %}
							<button class="glide__bullet" data-glide-dir="={{forloop.counter0}}"></button>
						{% endfor %}
					</div>
				</div>
			</div>
		{% endif %}

		{% if question.video_set.all %}
			<div class="glide-container" id="video-carousel">
				<div class="glide">
					<div class="glide__track" data-glide-el="track">
						<ul class="glide__slides">
							{% for video in question.video_set.all %}
								<li class="glide__slide">
									<div class="video-container">
										<video controls>
											<source src="{{video.video.url}}" type="video/mp4">
											Your browser does not support video tag.
										</video>
									</div>
								</li>
							{% endfor %}
						</ul>
					</div>
					<!-- <div class="glide__arrows" data-glide-el="controls">
						<button class="glide__arrow glide__arrow--left" data-glide-dir="<">{% translate "prev" context "carousel button" %}</button>
						<button class="glide__arrow glide__arrow--right" data-glide-dir=">">{% translate "next" context "carousel button" %}</button>
					</div> -->
					<div class="glide__bullets" data-glide-el="controls[nav]">
						{% for video in question.video_set.all %}
							<button class="glide__bullet" data-glide-dir="={{forloop.counter0}}"></button>
						{% endfor %}
					</div>
				</div>
			</div>
		{% endif %}
	</div>
    <div class="question-card-content">
        <div class="card-content-row">
            <label for="">{{question|verbose_name:"question_number"}}:</label>
            {{ question.question_number }}
        </div>
        <div class="card-content-row">
            <label for="">{{question|verbose_name:"question_text"}}: </label>
            {{ question.question_text }}
        </div>
        <div class="card-content-row">
            <label for="">{{question|verbose_name:"answer_text"}}:</label>
            {{ question.answer_text }}
    </div>
	<div class="button-wrapper">
		<a href="{% url 'bot:question-update' question.pk %}" class="btn">{% translate "Edit" %}</a>
		<a href="{% url 'bot:question-delete' question.pk %}" class="btn">{% translate "Delete" %}</a>
	</div>
</div>

{% endblock %}

{% block scripts %}
<script>
	let scale = 0.7;
	if (document.querySelector('#photo-carousel')) {
		new Glide('#photo-carousel .glide', {
			type: 'carousel',
			startAt: 0,
			perView: 1,
			focusAt: 'center',
			// gap: 50,
		}).mount();
	}
	
	if (document.querySelector('#video-carousel')) {
		new Glide('#video-carousel .glide', {
        type: 'carousel', 
        startAt: 0,
        perView: 1,
        focusAt: 'center',
    }).mount();
	}

    // Функция для определения высоты видимой области экрана
    function getViewportHeight() {
        return Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0);
    }

    // Функция для вычисления значения, равного высоте всей страницы минус высота хедера
    function calculateContentHeight() {
        var headerHeight = document.querySelector('.header').offsetHeight;
        var viewportHeight = getViewportHeight();
        var contentHeight = viewportHeight - headerHeight;

        // Используйте значение contentHeight по вашему усмотрению
        // console.log('Content Height:', contentHeight);
        return contentHeight;
    }

    // Функция для установки max-height для видео
    function setVideoHeight() {
        var height = calculateContentHeight(); // Используем ранее определенную функцию
        var videos = document.querySelectorAll('#video-carousel .video-container video');

        videos.forEach(function(video) {
            video.style.height = Math.floor(height * scale) + 'px';
        });
    }

	function setPhotoHeight() {
		var height = calculateContentHeight();
		var photos = document.querySelectorAll('.question-detail-image');
		photos.forEach(function(photo) {
			photo.style.height = Math.floor(height * scale) + 'px';
		});
	}

    // Вызовите функцию при загрузке страницы и изменении размера окна
    window.addEventListener('load', function() {
        setVideoHeight();
		setPhotoHeight();
    });

    window.addEventListener('resize', function() {
        setVideoHeight();
		setPhotoHeight();
    });
</script>
{% endblock %}